# '데이터 분석 numpy 기초 문법 노트북'
> '2021년 여름방학 데이터분석을 위한 numpy 기초문법'


- toc : true
- branch : master
- badges : true
- comments : true
- author : kang a-hyeon
- categories : [python, 데이터분석, numpy]

In [4]:
리스트 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
리스트[0][0]
리스트[0]
리스트[2][0]
리스트 * 2

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
import numpy as np

리스트 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
리스트 = np.array(리스트)
리스트 * 2
리스트 + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [9]:
a = np.arange(15).reshape(3, 5)  
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
a = np.arange(20).reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [16]:
a = np.arange(20).reshape(2, 2, 5)
a


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [17]:
a = np.arange(20).reshape(2, 2, 5)
a[0][1][2]

7

In [24]:
a = np.arange(15).reshape(3, 5)  
a
a.shape    #?행 ?열
a.ndim   #차원
a.dtype.name   #타입
a.size   #flat한 데이터 사이즈
type(a)  

numpy.ndarray

In [ ]:
np.zeros((3, 4))

In [25]:
np.ones((2, 3), dtype=np.int16)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [26]:
np.empty((2, 3))

array([[4.65670373e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [27]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [30]:
np.linspace(0, 9.5, 20)
np.linspace(0.5, 10, 20)                 


array([ 0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,
        6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [31]:
리스트 = [[10, 2, 3], [4, 5, 6], [7, 8, 9]]

a = np.array(리스트)
# a.sum(), sum(리스트)   #sum(리스트)는 에러납니다.
a.min(), min(리스트)
a.max(), max(리스트)   #2개는 출력하는 결과도 다릅니다.

(10, [10, 2, 3])

In [34]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
b.sum(axis=0)  # col기준으로 row끼리 더한 것(세로)
b.sum(axis=1)  # row기준으로 col끼리 더한 것(가로)
b.sum()  #flat하게 모두 더한 것

66

In [40]:
b.ravel()   #b를 평평하게 펴주는 것

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [42]:
b.T   #잘 써요!
#b.transpose()  잘 안 써요! (위의 코드와 같은 결과를 나타냄)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [46]:
a = np.array([[1,2],[3,4]])
b = np.floor([[5,6],[7,8]])
np.vstack((a, b))
np.hstack((a, b))


array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

In [44]:
# 매우 많이 사용되는 코드입니다.
a = np.arange(12).reshape(3, 4)
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [45]:
b.sum()

7